---
- hosts: all
  become: yes
  tasks:
    - name: Kill any running apt processes
      shell: |
        pkill -f apt || true
        pkill -f dpkg || true
        sleep 5
      ignore_errors: yes

    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      retries: 3
      delay: 10
      register: apt_update_result
      until: apt_update_result is succeeded

    - name: Install Apache and IPTables-Persistent
      apt:
        name:
          - apache2
          - iptables-persistent
        state: present
      retries: 3
      delay: 10

    - name: Flush all INPUT chain rules to ensure a clean slate
      iptables:
        chain: INPUT
        flush: yes

    - name: Re-insert rule to allow SSH traffic on port 22
      iptables:
        chain: INPUT
        action: insert
        rule_num: "1"
        protocol: tcp
        destination_port: "22"
        jump: ACCEPT
        comment: "Allow SSH traffic"

    - name: Insert rule to allow HTTP traffic on port 80
      iptables:
        chain: INPUT
        action: insert
        rule_num: "2"
        protocol: tcp
        destination_port: "80"
        jump: ACCEPT
        comment: "Allow HTTP traffic"
      notify: Save iptables rules

    - name: Create professional index.html with Load Balancer styling
      copy:
        content: |
          <!DOCTYPE html>
          <html lang="es">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>🚀 Servidor Web Enterprise {{ ansible_facts.hostname }} - OCI Load Balancer</title>
              <style>
                  * {
                      margin: 0;
                      padding: 0;
                      box-sizing: border-box;
                  }
                  body {
                      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      color: #333;
                  }
                  .container {
                      background: rgba(255, 255, 255, 0.95);
                      border-radius: 20px;
                      box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
                      backdrop-filter: blur(10px);
                      padding: 40px;
                      width: 90%;
                      max-width: 800px;
                      text-align: center;
                      border: 3px solid #667eea;
                  }
                  .server-badge {
                      display: inline-block;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      padding: 8px 20px;
                      border-radius: 25px;
                      font-weight: bold;
                      margin-bottom: 20px;
                      animation: pulse 2s infinite;
                  }
                  @keyframes pulse {
                      0% { transform: scale(1); }
                      50% { transform: scale(1.05); }
                      100% { transform: scale(1); }
                  }
                  h1 {
                      font-size: 2.5rem;
                      margin-bottom: 10px;
                      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1);
                      color: #2c3e50;
                  }
                  .subtitle {
                      font-size: 1.3rem;
                      color: #666;
                      margin-bottom: 30px;
                      font-weight: 300;
                  }
                  .architecture-info {
                      background: linear-gradient(135deg, #a8edea 0%, #fed6e3 100%);
                      padding: 20px;
                      border-radius: 15px;
                      margin: 20px 0;
                      border: 2px solid #667eea;
                  }
                  .architecture-title {
                      font-size: 1.5rem;
                      font-weight: bold;
                      color: #2c3e50;
                      margin-bottom: 10px;
                  }
                  .load-balancer-indicator {
                      display: inline-block;
                      background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
                      color: white;
                      padding: 5px 15px;
                      border-radius: 20px;
                      font-size: 0.9rem;
                      margin: 5px;
                      font-weight: bold;
                  }
                  .info-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                      gap: 20px;
                      margin: 30px 0;
                  }
                  .info-card {
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      padding: 20px;
                      border-radius: 15px;
                      box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
                      transition: transform 0.3s ease;
                  }
                  .info-card:hover {
                      transform: translateY(-5px);
                  }
                  .info-card h3 {
                      font-size: 1.1rem;
                      margin-bottom: 10px;
                      opacity: 0.9;
                  }
                  .info-card p {
                      font-size: 1.2rem;
                      font-weight: bold;
                  }
                  .status-section {
                      background: linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%);
                      padding: 20px;
                      border-radius: 15px;
                      margin: 20px 0;
                      border: 2px solid #4CAF50;
                  }
                  .status-indicator {
                      display: inline-block;
                      width: 12px;
                      height: 12px;
                      background: #4CAF50;
                      border-radius: 50%;
                      margin-right: 10px;
                      animation: blink 1.5s infinite;
                  }
                  @keyframes blink {
                      0%, 50% { opacity: 1; }
                      51%, 100% { opacity: 0.3; }
                  }
                  .tech-stack {
                      margin: 20px 0;
                  }
                  .tech-badge {
                      display: inline-block;
                      background: #34495e;
                      color: white;
                      padding: 5px 12px;
                      border-radius: 20px;
                      font-size: 0.8rem;
                      margin: 3px;
                      font-weight: bold;
                  }
                  .footer {
                      margin-top: 30px;
                      padding-top: 20px;
                      border-top: 2px solid #ecf0f1;
                      color: #666;
                      font-size: 0.9rem;
                  }
                  @media (max-width: 768px) {
                      .container {
                          padding: 20px;
                          width: 95%;
                      }
                      h1 {
                          font-size: 2rem;
                      }
                      .info-grid {
                          grid-template-columns: 1fr;
                      }
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="server-badge">🖥️ SERVIDOR BACKEND</div>
                  <h1>🚀 ¡LOAD BALANCER ACTIVO!</h1>
                  <p class="subtitle">Servidor Web Backend con Balanceador de Carga OCI</p>
                  
                  <div class="architecture-info">
                      <div class="architecture-title">03 - Balanceador de Carga OCI</div>
                      <div class="load-balancer-indicator">🔄 LOAD BALANCER</div>
                      <div class="load-balancer-indicator">⚖️ ALTA DISPONIBILIDAD</div>
                      <div class="load-balancer-indicator">🔀 DISTRIBUCIÓN DE CARGA</div>
                      <p style="margin-top: 15px; color: #2c3e50;">
                          <strong>Arquitectura:</strong> Este servidor forma parte de un pool de backend servers detrás de un Load Balancer de OCI que distribuye el tráfico automáticamente.
                      </p>
                  </div>
                  
                  <div class="info-grid">
                      <div class="info-card">
                          <h3>📍 IP Privada</h3>
                          <p>{{ ansible_facts.default_ipv4.address }}</p>
                      </div>
                      <div class="info-card">
                          <h3>🖥️ Hostname</h3>
                          <p>{{ ansible_facts.hostname }}</p>
                      </div>
                      <div class="info-card">
                          <h3>🐧 Sistema</h3>
                          <p>{{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}</p>
                      </div>
                      <div class="info-card">
                          <h3>⚖️ Balanceador</h3>
                          <p>OCI Load Balancer</p>
                      </div>
                  </div>
                  
                  <div class="status-section">
                      <h3 style="color: #2c3e50; margin-bottom: 15px;">
                          <span class="status-indicator"></span>Estado del Servidor
                      </h3>
                      <p style="color: #2c3e50; font-weight: bold;">
                          ✅ Servidor Backend Activo | 🔄 Balanceador de Carga Operativo | 🌐 Distribuyendo Tráfico
                      </p>
                      <div class="tech-stack">
                          <span class="tech-badge">🌊 OCI</span>
                          <span class="tech-badge">🏗️ Terraform</span>
                          <span class="tech-badge">🤖 Ansible</span>
                          <span class="tech-badge">🌐 Apache2</span>
                          <span class="tech-badge">⚖️ Load Balancer</span>
                          <span class="tech-badge">🔄 Backend Pool</span>
                      </div>
                  </div>
                  
                  <div class="footer">
                      <p><strong>🚀 Arquitectura:</strong> 03 - Balanceador de Carga OCI</p>
                      <p><strong>📅 Desplegado:</strong> <span id="deployDate"></span></p>
                      <p><strong>🖥️ Servidor:</strong> Backend Pool Member - Alta Disponibilidad</p>
                  </div>
              </div>
              
              <script>
                  document.getElementById('deployDate').textContent = new Date().toLocaleDateString('es-ES', {
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric',
                      hour: '2-digit',
                      minute: '2-digit'
                  });
              </script>
          </body>
          </html>
        dest: /var/www/html/index.html

    - name: Ensure Apache is running and enabled on boot
      systemd:
        name: apache2
        state: started
        enabled: yes

  handlers:
    - name: Save iptables rules
      command: netfilter-persistent save 