# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Volúmenes de Bloque Local"
description: "Arquitectura de referencia para implementar volúmenes de bloque locales con balanceador de carga, gateway NAT y host bastión en Oracle Cloud Infrastructure."
stackDescription: "Arquitectura de referencia para implementar volúmenes de bloque locales con balanceador de carga, gateway NAT y host bastión en Oracle Cloud Infrastructure."
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - region
  - webservice_ports
  - ssh_ports

- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_ocid
  - availablity_domain_name 
  - show_advanced 

- title: "Networking Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - VCN-CIDR
  - PrivateSubnet-CIDR
  - LBSubnet-CIDR
  - BastionSubnet-CIDR

- title: "Load Balancer Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - lb_shape
  - flex_lb_min_shape
  - flex_lb_max_shape

- title: "Compute Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - WebserverShape
  - WebserverFlexShapeOCPUS
  - WebserverFlexShapeMemory
  - BastionShape
  - BastionFlexShapeOCPUS
  - BastionFlexShapeMemory
  - instance_os
  - linux_os_version

- title: "Block Volume Optional Configuration"
  visible:
      and:
        - show_advanced
  variables:
  - volume_size_in_gbs
  - vpus_per_gb

- title: "File Storage Service Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - MountTargetIPAddress

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region where you deploy your Webserver"
    type: oci:identity:region:name
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment OCID"
    description: "Choose Comparment where you deploy your Webserver"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  availablity_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain"
    description: "Choose Availability Domain where your Webserver1 & Webserver2 will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  # Optional Configuration

  VCN-CIDR:
    type: string
    required: false
    default: "10.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose single, contiguous IPv4 CIDR block for the VCN"

  PrivateSubnet-CIDR:
    type: string
    required: false
    default: "10.0.1.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Private Subnet CIDR"
    description: "Choose single, contiguous IPv4 CIDR block for the Private Subnet"

  LBSubnet-CIDR:
    type: string
    required: false
    default: "10.0.2.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "LoadBalancer Subnet CIDR"
    description: "Choose single, contiguous IPv4 CIDR block for the Subnet"

  BastionSubnet-CIDR:
    type: string
    required: false
    default: "10.0.3.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Bastion Subnet CIDR"
    description: "Choose single, contiguous IPv4 CIDR block for the Subnet"

  WebserverShape:
    type: oci:core:instanceshape:name
    title: "Webserver Shape"
    description: "Choose a shape for your Webserver"
    default: "VM.Standard.A1.Flex"
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}

  WebserverFlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Webserver Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - WebserverShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - WebserverShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - WebserverShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - WebserverShape 
            - "VM.Optimized3.Flex"

  WebserverFlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "Webserver Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - WebserverShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - WebserverShape
            - "VM.Standard.E4.Flex"
          - eq:
            - WebserverShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - WebserverShape 
            - "VM.Optimized3.Flex"

  BastionShape:
    type: oci:core:instanceshape:name
    title: "Bastion Shape"
    description: "Choose a shape for your Bastion Host"
    default: "VM.Standard.A1.Flex"
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}

  BastionFlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Bastion Flex Shape OCPUs"
    description: "Choose number of OCPUs for Bastion Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - BastionShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - BastionShape 
            - "VM.Optimized3.Flex"

  BastionFlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "Bastion Flex Shape Memory (GB)"
    description: "Choose number GB for Bastion Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - BastionShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - BastionShape
            - "VM.Standard.E4.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - BastionShape 
            - "VM.Optimized3.Flex"

  instance_os:
    type: enum
    required: false
    default: "Canonical Ubuntu"
    title: "Instance OS"
    description: "An Operating System that determines the operating system for the instance."
    enum:
      - "Canonical Ubuntu"

  linux_os_version:
    type: enum
    required: false
    default: "22.04"
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for the instance."
    enum:
      - "22.04"

  lb_shape:
    type: enum
    title: "LoadBalancer Shape"
    description: "Choose LoadBalancer Shape"
    default: "flexible"
    required: false 
    enum:
      - "flexible"
      - "10Mbps"
      - "100Mbps"
      - "400Mbps"
      - "8000Mbps"

  flex_lb_min_shape:
    type: enum
    required: false
    default: "10"
    title: "LoadBalancer Flex Min Shape"
    description: "Choose Minimum Shape for Flex LoadBalancer."
    enum:
      - "10"
      - "100"
      - "1000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  flex_lb_max_shape:
    type: enum
    required: false
    default: "100"
    title: "LoadBalancer Flex Max Shape"
    description: "Choose Maximum Shape for Flex LoadBalancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  volume_size_in_gbs:
    type: number
    required: false
    minimum: 50
    maximum: 32768
    multipleOf: 1
    default: 100
    title: "Block Volume Size (GB)"
    description: "Choose Block Volume Size (min 50GB)"

  vpus_per_gb:
    type: enum
    required: false
    default: "10"
    title: "Block Volume Performance"
    description: "Choose Block Volume Performance"
    enum:
      - "0"
      - "10"
      - "20"
      - "30"

  MountTargetIPAddress:
    type: string
    required: false
    default: "10.0.1.25"
    title: "Mount Target IP Address"
    description: "Choose Mount Target IP Address (should be within PrivateSubnet CIDR)"

  webservice_ports:
    type: array
    items:
      type: string
    required: false
    default: ["80","443"]
    title: "Webservice Ports"
    description: "Choose Webservice Ports to be allowed by Security Lists"

  ssh_ports:
    type: array
    items:
      type: string
    required: false
    default: ["22"]
    title: "SSH Ports"
    description: "Choose SSH Ports to be allowed by Security Lists"

outputs:

  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: string
    visible: true
  
  FoggyKitchenWebserver1PrivateIP:
    title: "Webserver1 Private IP"
    displayText: "Webserver1 Private IP"
    type: copyableString
    visible: true

  FoggyKitchenWebserver2PrivateIP:
    title: "Webserver2 Private IP"
    displayText: "Webserver2 Private IP"
    type: copyableString
    visible: true

  FoggyKitchenPublicLoadBalancer_Public_IP:
    title: "LoadBalancer Public IP"
    displayText: "LoadBalancer Public IP"
    type: copyableString
    visible: true


