---
- hosts: all
  become: yes
  tasks:
    - name: Kill any running apt processes
      shell: |
        pkill -f apt || true
        pkill -f dpkg || true
        sleep 5
      ignore_errors: yes

    - name: Preseed iptables-persistent to avoid interactive prompts
      debconf:
        name: iptables-persistent
        question: iptables-persistent/autosave_v4
        value: "true"
        vtype: boolean

    - name: Preseed iptables-persistent IPv6 to avoid interactive prompts
      debconf:
        name: iptables-persistent
        question: iptables-persistent/autosave_v6
        value: "true"
        vtype: boolean

    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      retries: 3
      delay: 10
      register: apt_update_result
      until: apt_update_result is succeeded

    - name: Install Apache and IPTables-Persistent
      apt:
        name:
          - apache2
          - iptables-persistent
        state: present
      retries: 3
      delay: 10
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Flush existing INPUT chain rules to start clean
      iptables:
        chain: INPUT
        flush: yes
      ignore_errors: yes

    - name: Allow established and related connections
      iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
        comment: "Allow established and related connections"

    - name: Allow loopback traffic
      iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT
        comment: "Allow loopback traffic"

    - name: Allow SSH traffic on port 22
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "22"
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
        comment: "Allow SSH traffic"

    - name: Allow HTTP traffic on port 80
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "80"
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
        comment: "Allow HTTP traffic"

    - name: Allow HTTPS traffic on port 443
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "443"
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
        comment: "Allow HTTPS traffic"

    - name: Drop all other traffic (set default policy last)
      iptables:
        chain: INPUT
        policy: DROP

    - name: Save iptables rules
      command: netfilter-persistent save

    - name: Create enhanced index.html with modern design
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html lang="es">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>🚀 Servidor Web Enterprise - OCI Terraform</title>
              <style>
                  * {
                      margin: 0;
                      padding: 0;
                      box-sizing: border-box;
                  }
                  
                  body {
                      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      padding: 20px;
                  }
                  
                  .container {
                      background: rgba(255, 255, 255, 0.95);
                      border-radius: 20px;
                      padding: 40px;
                      box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
                      text-align: center;
                      max-width: 600px;
                      width: 100%;
                      backdrop-filter: blur(10px);
                  }
                  
                  .header {
                      color: #333;
                      font-size: 2.5rem;
                      margin-bottom: 20px;
                      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1);
                  }
                  
                  .subtitle {
                      color: #666;
                      font-size: 1.3rem;
                      margin-bottom: 30px;
                      font-weight: 300;
                  }
                  
                  .info-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                      gap: 20px;
                      margin: 30px 0;
                  }
                  
                  .info-card {
                      background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
                      color: white;
                      padding: 20px;
                      border-radius: 15px;
                      box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
                      transition: transform 0.3s ease;
                  }
                  
                  .info-card:hover {
                      transform: translateY(-5px);
                  }
                  
                  .info-card h3 {
                      font-size: 1.1rem;
                      margin-bottom: 8px;
                      opacity: 0.9;
                  }
                  
                  .info-card p {
                      font-size: 1.3rem;
                      font-weight: bold;
                  }
                  
                  .tech-stack {
                      background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
                      color: white;
                      padding: 20px;
                      border-radius: 15px;
                      margin: 30px 0;
                      box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
                  }
                  
                  .tech-stack h3 {
                      margin-bottom: 15px;
                      font-size: 1.4rem;
                  }
                  
                  .tech-list {
                      display: flex;
                      flex-wrap: wrap;
                      justify-content: center;
                      gap: 10px;
                  }
                  
                  .tech-badge {
                      background: rgba(255, 255, 255, 0.2);
                      padding: 8px 16px;
                      border-radius: 25px;
                      font-size: 0.9rem;
                      font-weight: bold;
                      backdrop-filter: blur(5px);
                  }
                  
                  .status {
                      background: linear-gradient(135deg, #a8edea 0%, #fed6e3 100%);
                      color: #333;
                      padding: 20px;
                      border-radius: 15px;
                      margin-top: 30px;
                      box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
                  }
                  
                  .status-indicator {
                      width: 12px;
                      height: 12px;
                      background: #4CAF50;
                      border-radius: 50%;
                      display: inline-block;
                      margin-right: 8px;
                      box-shadow: 0 0 10px rgba(76, 175, 80, 0.5);
                  }
                  
                  .timestamp {
                      color: #888;
                      font-size: 0.9rem;
                      margin-top: 20px;
                  }
                  
                  @media (max-width: 768px) {
                      .header {
                          font-size: 2rem;
                      }
                      
                      .container {
                          padding: 30px 20px;
                      }
                      
                      .info-grid {
                          grid-template-columns: 1fr;
                      }
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1 class="header">🚀 ¡VICTORIA!</h1>
                  <p class="subtitle">Servidor Web Desplegado con Terraform y Ansible</p>
                  
                  <div class="info-grid">
                      <div class="info-card">
                          <h3>🏗️ Arquitectura</h3>
                          <p>01 - Servidor Web Único</p>
                      </div>
                      <div class="info-card">
                          <h3>🌐 IP Privada</h3>
                          <p>{{ ansible_facts.default_ipv4.address }}</p>
                      </div>
                      <div class="info-card">
                          <h3>🔧 Hostname</h3>
                          <p>{{ ansible_facts.hostname }}</p>
                      </div>
                      <div class="info-card">
                          <h3>💻 Sistema</h3>
                          <p>{{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}</p>
                      </div>
                  </div>
                  
                  <div class="tech-stack">
                      <h3>🛠️ Stack Tecnológico</h3>
                      <div class="tech-list">
                          <span class="tech-badge">Oracle Cloud Infrastructure</span>
                          <span class="tech-badge">Terraform</span>
                          <span class="tech-badge">Ansible</span>
                          <span class="tech-badge">Apache2</span>
                          <span class="tech-badge">Ubuntu 22.04</span>
                          <span class="tech-badge">VM.Standard.E3.Flex</span>
                      </div>
                  </div>
                  
                  <div class="status">
                      <h3><span class="status-indicator"></span>Estado del Servidor</h3>
                      <p>✅ Servidor Web Activo y Funcionando</p>
                      <p>🔒 Firewall Configurado</p>
                      <p>🌐 Acceso Público Habilitado</p>
                  </div>
                  
                  <div class="timestamp">
                      <p>Desplegado el: <span id="deployment-date"></span></p>
                  </div>
              </div>
              
              <script>
                  // Mostrar fecha de despliegue
                  document.getElementById('deployment-date').textContent = new Date().toLocaleDateString('es-ES', {
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric',
                      hour: '2-digit',
                      minute: '2-digit'
                  });
              </script>
          </body>
          </html>

    - name: Ensure Apache is running and enabled on boot
      systemd:
        name: apache2
        state: started
        enabled: yes